from .cross_entropy import LabelSmoothingCrossEntropy, SoftTargetCrossEntropy, WeightedSoftTargetCrossEntropy
from .jsd import JsdCrossEntropy
from .asymmetric_loss import AsymmetricLossMultiLabel, AsymmetricLossSingleLabel